In [220]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)

import re

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer

from sklearn.metrics import accuracy_score
from sklearn import model_selection, preprocessing, linear_model

from sklearn.decomposition import PCA   # метод главных компонент

In [148]:
combine = pd.read_pickle("./combine_df.pkl")
combine

,id,label,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,when father is dysfunctional and is so selfish...,when father is dysfunctional and is so selfish...,father dysfunctional selfish drags kids dysfu...,father dysfunct selfish drag kid dysfunct run,father dysfunctional selfish drag kid dysfunc...
1,2,0.0,thanks for lyft credit cannot use cause they d...,thanks for lyft credit can not use cause they ...,thanks lyft credit use cause offer wheelchair ...,thank lyft credit use caus offer wheelchair va...,thanks lyft credit use cause offer wheelchair ...
2,3,0.0,bihday your majesty,bihday your majesty,bihday majesty,bihday majesti,bihday majesty
3,4,0.0,model love you take with you all the time in your,model love you take with you all the time in your,model love take time,model love take time,model love take time
4,5,0.0,factsguide society now motivation,factsguide society now motivation,factsguide society motivation,factsguid societi motiv,factsguide society motivation
...,...,...,...,...,...,...,...
49154,49155,NaN,thought factory left right polarisation trump ...,thought factory left right polarisation trump ...,thought factory left right polarisation trump ...,thought factori left right polaris trump usele...,thought factory left right polarisation trump ...
49155,49156,NaN,feeling like mermaid hairflip neverready forma...,feeling like mermaid hairflip neverready forma...,feeling like mermaid hairflip neverready forma...,feel like mermaid hairflip neverreadi formal w...,feeling like mermaid hairflip neverready forma...
49156,49157,NaN,hillary campaigned today in ohio omg used word...,hillary campaigned today in ohio omg used word...,hillary campaigned today ohio omg used words l...,hillari campaign today ohio omg use word like ...,hillary campaigned today ohio omg used word li...
49157,49158,NaN,happy at work conference right mindset leads t...,happy at work conference right mindset leads t...,happy work conference right mindset leads cult...,happi work confer right mindset lead cultur de...,happy work conference right mindset lead cultu...
49158,49159,NaN,my song so glad free download shoegaze newmusi...,my song so glad free download shoegaze newmusi...,song glad free download shoegaze newmusic new...,song glad free download shoegaz newmus newsong,song glad free download shoegaze newmusic new...

### 1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
#### Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
#### Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
#### Исключим стоп-слова с помощью stop_words='english'.
#### Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().

In [149]:
count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', binary=False, max_df=0.9, 
                                   max_features = 1000, stop_words='english')

In [150]:
# Создаем the Bag-of-Words модель
bag_of_words_st = count_vectorizer.fit_transform(combine['tweet_stemmed'])
bag_of_words_st

<49159x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 203414 stored elements in Compressed Sparse Row format>

In [151]:
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words_st.toarray(), columns = feature_names)

,abl,absolut,accept,account,act,action,activ,actor,actual,ad,...,year,yesterday,yo,yoga,york,young,youtub,yoyou,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49155,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49156,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49157,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49158,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [152]:
# Создаем the Bag-of-Words модель
bag_of_words_lm = count_vectorizer.fit_transform(combine['tweet_lemmatized'])
bag_of_words_lm

<49159x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 187392 stored elements in Compressed Sparse Row format>

In [153]:
# Отобразим Bag-of-Words модель как DataFrame
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words_lm.toarray(), columns = feature_names)

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yes,yesterday,yo,yoga,york,young,youtube,yoyou,yr,yummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49155,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49156,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49157,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49158,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
#### Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
#### Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
#### Исключим стоп-слова с помощью stop_words='english'.
#### Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().

In [154]:
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1, 1), analyzer='word', binary=False, max_df=0.9, 
                                   max_features = 1000, stop_words='english')
bag_of_words_st = tfidf_vectorizer.fit_transform(combine['tweet_stemmed'])

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words_st.toarray(), columns = feature_names)

,abl,absolut,accept,account,act,action,activ,actor,actual,ad,...,year,yesterday,yo,yoga,york,young,youtub,yoyou,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49156,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [155]:
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1, 1), analyzer='word', binary=False, max_df=0.9, 
                                   max_features = 1000, stop_words='english')
bag_of_words_lm = tfidf_vectorizer.fit_transform(combine['tweet_lemmatized'])

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words_lm.toarray(), columns = feature_names)

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yes,yesterday,yo,yoga,york,young,youtube,yoyou,yr,yummy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49156,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 3. Создайте мешок слов с помощью sklearn.feature_extraction.text.HashingVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
#### Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
#### Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.(можно изменить)
#### Исключим стоп-слова с помощью stop_words='english'.

In [163]:
vectorizer = HashingVectorizer(n_features=2**4, ngram_range=(1, 1), analyzer='word', binary=False, stop_words='english')

In [167]:
bag_of_words_st = vectorizer.fit_transform(combine['tweet_stemmed'])
print(bag_of_words_st.shape)
print(bag_of_words_st.toarray())

(49159, 16)
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.33333333  0.         ...  0.          0.33333333
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [-0.43643578 -0.21821789  0.         ...  0.         -0.21821789
   0.21821789]
 [ 0.          0.5547002   0.         ... -0.2773501   0.
   0.2773501 ]
 [-0.4472136   0.          0.         ... -0.4472136   0.4472136
   0.        ]]

In [168]:
bag_of_words_lm = vectorizer.fit_transform(combine['tweet_lemmatized'])
print(bag_of_words_lm.shape)
print(bag_of_words_lm.toarray())

(49159, 16)
[[ 0.          0.          0.         ...  0.57735027  0.
   0.        ]
 [ 0.33333333  0.33333333  0.33333333 ...  0.          0.33333333
  -0.33333333]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [-0.45883147 -0.22941573 -0.22941573 ...  0.         -0.22941573
   0.        ]
 [ 0.          0.60302269 -0.30151134 ...  0.30151134 -0.30151134
   0.30151134]
 [ 0.          0.          0.         ... -0.4472136   0.4472136
   0.        ]]

### 4. Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте таблицу метод векторизации и скор который вы получили (в методах векторизации по изменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы

In [169]:
# Загружаем данные
data = open('corpus').read()
labels, texts = [], []
for i, line in enumerate(data.split("\n")):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))

# создаем df
trainDF = pd.DataFrame()
trainDF['text'] = texts
trainDF['label'] = labels
trainDF.head(5)

                                                text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2
3  Excellent Soundtrack: I truly like this soundt...  __label__2
4  Remember, Pull Your Jaw Off The Floor After He...  __label__2

In [180]:
trainDF['label'].value_counts()

__label__1    5097
__label__2    4903
Name: label, dtype: int64

In [176]:
linear_model.LogisticRegression()

LogisticRegression()

In [218]:
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(trainDF['text'], trainDF['label'])

# labelEncode целевую переменную
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)


count_vect = CountVectorizer(analyzer='word', max_features = 10000, max_df=0.9)
count_vect.fit(trainDF['text'])

xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions = classifier.predict(xvalid_count)
predictions

/home/tefi/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([1, 1, 1, ..., 0, 0, 0])

In [219]:
accuracy_score(valid_y, predictions)

0.8636

In [226]:
trainDF['text']

0       Stuning even for the non-gamer: This sound tra...
1       The best soundtrack ever to anything.: I'm rea...
2       Amazing!: This soundtrack is my favorite music...
3       Excellent Soundtrack: I truly like this soundt...
4       Remember, Pull Your Jaw Off The Floor After He...
                              ...
9995    A revelation of life in small town America in ...
9996    Great biography of a very interesting journali...
9997    Interesting Subject; Poor Presentation: You'd ...
9998    Don't buy: The box looked used and it is obvio...
9999    Beautiful Pen and Fast Delivery.: The pen was ...
Name: text, Length: 10000, dtype: object

In [229]:
count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', binary=False, max_df=0.9, 
                                   max_features = 10000, stop_words='english')

In [230]:
bag_of_words_st = count_vectorizer.fit_transform(trainDF['text'])
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words_st.toarray(), columns = feature_names)

,00,000,001,01,03,04,05,06,07,10,...,zodiac,zoe,zombie,zombies,zone,zoom,zoot,zr,zr40,zzzzz
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [231]:
text_d = pd.DataFrame(bag_of_words_st.toarray(), columns = feature_names)
text_d

,00,000,001,01,03,04,05,06,07,10,...,zodiac,zoe,zombie,zombies,zone,zoom,zoot,zr,zr40,zzzzz
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [232]:
pca = PCA(n_components=4000)
N_1 = pca.fit_transform(text_d.loc[:,:].values)
pca.explained_variance_ratio_[:2].sum()

0.05747319985056211